app/__init__.py
from flask import Flask
from config import Config
from.site.routes import site
from.api.routes import api
from.authentication.routes import auth


from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder


app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import Blueprint, request, jsonify, render_template
from helpers import token_required
from models import db, User, Library, lib_schema, libs_schema

api = Blueprint('api',__name__, url_prefix='/api')

@api.route('/getdata')
def getdata():
    return {'read': 'books'}

# @api.route('/data')
# def viewdata():
#     data = get_contact()
#     response = jsonify(data)
#     print(response)
#     return render_template('index.html', data = data)

@api.route('/ebooks', methods = ['POST'])
@token_required
def create_book(current_user_token):
    isbn = request.json['isbn']
    book_title = request.json['book_title']
    author_name = request.json['author_name']
    book_length = request.json['book_length']
    publisher = request.json['publisher']
    book_format = request.json['book_format']
    user_token = current_user_token.token

    print(f'BIG TESTER: {current_user_token.token}')

    digital_library = Library(isbn, book_title, author_name, book_length, publisher, book_format, user_token = user_token )

    db.session.add(digital_library)
    db.session.commit()

    response = lib_schema.dump(digital_library)
    return jsonify(response)

@api.route('/ebooks', methods = ['GET'])
@token_required
def retrieve_single_book(current_user_token):
    _book = current_user_token.token
    libs = Library.query.filter_by(user_token = _book).all()
    response = libs_schema.dump(libs)
    return jsonify(response)

@api.route('/ebooks/<id>', methods = ['GET'])
@token_required
def retrieve_all_books(current_user_token, id):
    fan = current_user_token.token
    if fan == current_user_token.token:
        digital_library = Library.query.get(id)
        response = lib_schema.dump(digital_library)
        return jsonify(response)
    else:
        return jsonify({"message": "Valid Token Required"}),401

# UPDATE endpoint
@api.route('/ebooks/<id>', methods = ['POST','PUT'])
@token_required
def update_book(current_user_token,id):
    digital_library = Library.query.get(id) 
    digital_library.isbn = request.json['isbn']
    digital_library.book_title = request.json['book_title']
    digital_library.author_name = request.json['author_name']
    digital_library.book_length = request.json['book_length']
    digital_library.publisher = request.json['publisher']
    digital_library.book_format = request.json['book_format']
    digital_library.user_token = current_user_token.token

    db.session.commit()
    response = lib_schema.dump(digital_library)
    return jsonify(response)


# DELETE book ENDPOINT
@api.route('/ebooks/<id>', methods = ['DELETE'])
@token_required
def delete_book(current_user_token, id):
    digital_library = Library.query.get(id)
    db.session.delete(digital_library)
    db.session.commit()
    response = lib_schema.dump(digital_library)
    return jsonify(response)

app/authentication/routes.py
from forms import UserLoginForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash

# imports for flask login 
from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            # print(email, password)

            user = User(email, password = password)

            db.session.add(user)
            db.session.commit()
            
            flash(f'You have successfully created a user account {email}')
            return redirect(url_for('site.home'))
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('sign_up.html', form=form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            # print(email,password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('Auth-Sucess')
                return redirect(url_for('site.profile'))
            else:
                flash('Auth-Failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Login Data: Please Check your login information')
    return render_template('log_in.html', form=form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder='site_templates')

# default page start
@site.route('/')
def home():
    return render_template('index.html')
# default page end

@site.route('/profile')
def profile():
    return render_template('profile.html')

@site.route('/ebooks')
def ebooks():
    return render_template('ebooks.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="static/css/main.css">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:&display=swap" rel="stylesheet">
<title>Readerly</title>
</head>
<body style="background-color:white;">
    <div class="container">
    <nav class="navbar navbar-expand-sm  navbar-custom  navbar-static-top">
        <div class="container">
            <a href= "{{ url_for('site.home') }}"
            class="navbar-brand  navbar-text px-5">Readerly
            <img src="../static/images/logo/book icon.png" alt="" style="width: 30px; height: auto;">
            </a>
            <button 
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navmenu"
            >
            <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navmenu">
            <ul class="navbar-nav ms-auto">
                
                
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a href="{{ url_for('site.profile') }}" 
                    class="nav-link  navbar-text">
                    <button class="btn btn-outline-light" 
                    type="button" style="width: 5em;">Profile</button>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('auth.logout') }}" 
                    class="nav-link  navbar-text">
                    <button class="btn btn-outline-light" 
                    type="button" style="width: 5em;">Logout</button>
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{{ url_for('auth.signin') }}" 
                    class="nav-link  navbar-text">
                    <button class="btn btn-outline-light" 
                    type="button" style="width: 5em;">Login</button>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('auth.signup') }}" 
                    class="nav-link  navbar-text">
                    <button class="btn btn-outline-light" 
                    type="button" style="width: 5em;">Sign Up</button>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
 </nav>
</div>
<!-- End of Nav -->
{% block content %}
{% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset style="color: white;" id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', 
            placeholder = 'Enter email here ') }}
        </fieldset>
    </div>

        <fieldset style="color: white; padding-top: 2em;" id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", 
            placeholder = "Enter password here ") }}
        </fieldset>

        <!-- Submit button area -->
        <div class="col d-flex justify-content-center pt-4">
            {{ form.submit_button(class = "btn button btn-block mt-2")}}
        </div>
    

</form>